version: '3'

services:

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nodenet
    depends_on:
      - node

  node:
    container_name: node
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./node/main:/usr/src/app/main
    networks:
      - nodenet
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3306:3306"
    networks:
      - nodenet

networks:
  nodenet:
    driver: bridge